### ISSUE TITLE
after the last update

### ISSUE THREAD

**Issue by thewolfeds** [Fy-/FyPress#8]
fresh installation of this error
# python manager.py init_db

Traceback (most recent call last):
  File "manager.py", line 2, in <module>
    from fypress import FyPress
  File "/home/lanchesgli/FyPress0/fypress/**init**.py", line 2, in <module>
    from .fypress import FyPress
  File "/home/lanchesgli/FyPress0/fypress/fypress.py", line 7, in <module>
    from flask_fysql import FySQL
  File "/home/lanchesgli/FyPress0/fypress/flask_fysql.py", line 2, in <module>
    from fysql.databases import MySQLDatabase
ImportError: No module named fysql.databases

**Comment by Fy-** [comment]
Hey, I just updated requirements.txt. It was an issue with fysql version. It should be ok now. 

```
git clone git@github.com:Fy-/FyPress.git
cd FyPress
virtualenv env
source env/bin/activate
pip install -r requirements.txt
```

Edit your config.py with mysql db informations and run manager again:

```
python manager.py init_db
python manager.py init_fypress --login=fy --email=m@fy.to --password=mypwd
python run.py
```

Keep me informed :)
